on:
  push:
    tags:
      - 'v*'

name: Create Release
jobs:
  version: 
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        uses: battila7/get-version-action@v2
    outputs:
      major: ${{ steps.get_version.outputs.major }}
      minor: ${{ steps.get_version.outputs.minor }}
      patch: ${{ steps.get_version.outputs.patch }}
  build:
    needs: version
    uses: ./.github/workflows/pio-build.yaml
    with:
      major: ${{ needs.version.outputs.major }}
      minor: ${{ needs.version.outputs.minor }}
      patch: ${{ needs.version.outputs.patch }}
  release:
    needs: build
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Get current tag
        id: tag
        run: echo "::set-output name=tag::${GITHUB_REF##*/}"
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        id: download
        with:
          path: dist
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Zip
        run: zip -j ${{ steps.tag.outputs.tag }}-dist.zip ./dist/${{ needs.build.outputs.artifact }}/*
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.tag.outputs.tag }}-dist.zip
          asset_name: ${{ steps.tag.outputs.tag }}-dist.zip
          asset_content_type: application/zip

