name: PlatformIO CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current branch
        id: branch
        run: echo "::set-output name=branch::${GITHUB_REF##*/}"
      - name: Get current datetime
        id: datetime
        run: echo "::set-output name=datetime::$(date +'%Y%m%dT%H%M%S')"
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: '${{ runner.os }}-pip-${{ hashFiles(''**/requirements.txt'') }}'
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: '${{ runner.os }}-${{ hashFiles(''**/lockfiles'') }}'
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Install libs
        run: |
          cd SmartEVSE-3
          pio lib install
      - name: Fix modbus
        run: |
          sed -i '197 i serial.read(); //See https://github.com/SmartEVSE/SmartEVSE-3/issues/2 and https://github.com/eModbus/eModbus/issues/170' ./SmartEVSE-3/.pio/libdeps/release/eModbus/src/RTUutils.cpp
          sed -i '326 s/./\/\/&/' ./SmartEVSE-3/.pio/libdeps/release/eModbus/src/RTUutils.cpp
          cat ./SmartEVSE-3/.pio/libdeps/release/eModbus/src/RTUutils.cpp
      - name: Build
        run: pio run -d SmartEVSE-3/ -c SmartEVSE-3/platformio.ini
      - name: Build spiffs
        run: pio run -d SmartEVSE-3/ -c SmartEVSE-3/platformio.ini -t buildfs
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ steps.branch.outputs.branch }}-${{ steps.datetime.outputs.datetime }}
          path: ./SmartEVSE-3/.pio/build/release/*.bin
          retention-days: 10
